version: '3'
services:
  zomboid-server:
    image: renegademaster/zomboid-dedicated-server:latest
    container_name: zomboid-server
    restart: on-failure:3
    environment:
      - ADMIN_PASSWORD=default
      - MAP_NAMES=Riverside,KY
      - MAX_PLAYERS=5
      - MAX_RAM=2000m
      - MOD_NAMES=ReducedWoodWeight2x41;BB_CommonSense;NoLighterNeeded;improvedbackpacks;improvedbackpacksauthenticZ;improvedbackpacksclothesboxredux;improvedbackpacksspiffoBackpack;improvedbackpacksundeadSurvivor;ImprovisedBackpacks;ImprovisedSilencers;ImprovisedSilencersVFEPatch;SkillRecoveryJournal;AliceSPack;AmmoMaker;Barco;BatesMetalicosRevived;CustomMapBridge;Factory;FuelTanksMod;LeGourmetRevolution;LootZetaEnhancedEdition;MilitaryComplex;RPropaneTank;Riverside;SkillsMag;SnakeUtilsPack;SnakeClothingMod;SnakeMansion;TableSaw;TallerMecanico;WPA;TMC_TrueActions;tsarslib;TheStar;wellsConstruction
      - MOD_WORKSHOP_IDS=2377867605;2875848298;2714198296;2707607167;2471844569;2799742455;2503622437;2719327441;2487022075;2392709985;2619072426;2852690210
      - PAUSE_ON_EMPTY=true
      - SERVER_NAME=ApocalipsisZomboid
      - SERVER_PASSWORD=default
      - STEAM_VAC=true
      - USE_STEAM=true
    ports:
      - 16261:16261/udp
      - 16262:16262/udp
      - 27015:27015/tcp
    volumes:
      - zomboidDedicatedServer:/home/steam/ZomboidDedicatedServer
      - zomboidConfig:/home/steam/Zomboid

volumes:
  zomboidDedicatedServer:
  zomboidConfig:
